config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|sk/ do
    root to: 'tournaments#index'
    get '/:locale' => 'tournaments#index'

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    get 'static_pages/about'

    resources :tournaments do
      resources :courts do
        post :reorder_matches, on: :member
        resources :matches, only: [:new] do
          post :reorder, on: :collection
        end
      end
      resources :matches do
        get :edit_score, on: :member
        post :update_score, on: :member
      end
      get :refresh_score, on: :member
    end
  end
end

app/models/tournament.rb
class Tournament < ApplicationRecord

  belongs_to :user
  has_many :courts, inverse_of: :tournament, dependent: :destroy
  has_many :matches, through: :courts
  accepts_nested_attributes_for :courts, reject_if: :all_blank, allow_destroy: true

  validates :label, presence: true
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :refresh_score]
  before_action :load_tournament_or_redirect, only: [:edit, :update, :destroy, :refresh_score]
  before_action :set_tournament_progress, only: :show

  def index
    redirect_to new_user_session_path and return unless user_signed_in?
    redirect_to current_user.tournament and return if current_user.tournament.present?
  end

  def show
    @tournament = Tournament.find_by(id: params[:id])
    @court_public_keys = @tournament.courts.map(&:public_key) if @tournament.present?
  end

  def new
    authorize Tournament
    @tournament = Tournament.new(
      courts: [
        Court.new(label: '1'),
        Court.new(label: '2'),
        Court.new(label: '3')
      ]
    )
  end

  def create
    authorize Tournament
    @tournament = Tournament.new whitelisted_params
    @tournament.user = current_user

    if @tournament.save
      redirect_to @tournament
    else
      render :new
    end
  end

  def edit
    authorize @tournament
  end

  def update
    authorize @tournament
    @tournament.assign_attributes whitelisted_params

    if @tournament.save
      redirect_to @tournament
    else
      render :edit
    end
  end

  def destroy
    authorize @tournament
    @tournament.destroy
    redirect_to tournaments_path
  end

  def refresh_score
    respond_to do |format|
      format.js
    end
  end


  private

  def load_tournament_or_redirect
    @tournament = Tournament.find_by(id: params[:id])

    unless @tournament.present?
      redirect_to_root
      return
    end
  end

  def whitelisted_params
    params.require(:tournament).permit(
      :label, :public_score_update, courts_attributes: [:label, :id, :_destroy]
    )
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
  def court_label_for(match)
    "#{match.participant1}<br>vs<br>#{match.participant2}".html_safe
  end
end

app/views/tournaments/_court.html.erb
<div class="col-md-6 col-lg-4">
  <div class="card card-block text-center my-1 bg-court">
    <div class="bground"></div>
    <div class="court-content">
      <div class="card-body">
        <h5 class="card-title"><%= court.label %></h5>
        <% if court.matches.where(finished_at: nil).any? %>
          <%= render partial: 'play_info',
              locals: { current_match: court.current_match, next_match: court.next_match } %>
        <% else %>
          <p>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><small><%= t '.no_matches' %></small></li>
            </ul>
          </p>
        <% end %>
        <div><%= link_to t('.go_to_court'), tournament_court_path(@tournament, court), class: 'btn btn-sm btn-success' %></div>
      </div>
    </div>
  </div>
</div>

app/views/tournaments/_court_fields.html.erb
<div class="nested-fields">
  <div class="form-group clearfix">
    <div class="field">
      <%= f.label :label, t('.label') %>
      <%= f.text_field :label, class: 'form-control' %>
    </div>
    <%= link_to_remove_association '', f, class: 'float-right' %>
  </div>
</div>

app/views/tournaments/_courts.html.erb
<% @tournament.courts.sorted.includes(matches: :game_sets).each do |court| %>
  <%= render partial: 'court', locals: { court: court } %>
<% end %>

app/views/tournaments/_form.html.erb
<%= form_for @tournament do |f| %>
  <div class="row">
    <div class="col-md-7">
      <div class="form-group">
        <%= f.label :label, t('.label') %>
        <%= f.text_field :label, class: add_error_class_to('form-control', @tournament, :label), autofocus: true %>
      </div>
    </div>
    <div class="col-md-5 d-flex align-items-center">
      <div class="form-group form-check">
        <%= f.check_box :public_score_update, class: 'form-check-input' %>
        <label class="form-check-label" for="tournament_public_score_update">
          <%= t '.score_update_links_accessible' %>
        </label>
        <span data-toggle="tooltip" data-placement="bottom", title="<%= t('.public_score_update_info') %>">
          <%= fa_icon 'question-circle' %>
        </span>
      </div>
    </div>
  </div>
  <hr/>

  <h2 class="mb-4"><%= t '.courts' %></h2>
  <div id="courts">
    <div class="row">
      <div class="col-md-3">
        <%= f.fields_for :courts do |cf| %>
          <%= render 'court_fields', f: cf %>
        <% end %>
        <div class="links">
          <hr>
          <%= link_to_add_association t('.add_court'), f, :courts, class: 'btn btn-sm btn-outline-success' %>
        </div>
      </div>
    </div>
  </div>

  <p class="text-right">
    <%= link_to t('.back'), root_path, class: 'btn btn-lg btn-outline-success my-1' %>
    <%= f.submit t('.submit'), class: 'btn btn-lg btn-success my-1' %>
  </p>
<% end %>

<%= render 'scripts_form' %>

app/views/tournaments/_form_scripts.html.erb
<!-- Don't move this file to assets, scripts do not execute correctly on page load! -->

<script type='text/javascript'>
  // Functions

  // Draws X icon on .remove_fields elements
  function drawXIcons() {
    var removeLinks = $('.remove_fields');
    $(removeLinks).html('');
    $(removeLinks).append('<i class="fa fa-times"></i>');
  }


  // When document is ready...
  $(document).on('turbolinks:load', function() {
    drawXIcons();

    // Activate bootstrap tooltips
    $(function () {
      $('[data-toggle="tooltip"]').tooltip();
    });


    // Events

    // Suggest court label when new court-fields are being inserted
    $('#courts').on('cocoon:before-insert', function(e, insertedItem) {
      var calculatedCourtNr = $('#courts').find(".field").length + 1;
      $(insertedItem.find("input")[0]).val(calculatedCourtNr);
    });

    // Draw X icons after new court-field has been inserted
    $('#courts').on('cocoon:after-insert', function(e, insertedItem) {
      drawXIcons();
    });
  });
</script>

app/views/tournaments/_play_info.html.erb
<p>
  <ul class="list-group list-group-flush">
    <% if current_match.present? %>
      <li class="list-group-item">
        <p class="card-text mb-0">
          <strong><%= court_label_for current_match %></strong>
        </p>
        <p class="card-text">
          <span class="score animate-refresh"><%= Score.result_for current_match %></span><br>
          <small class="text-muted">
            <%= latest_score_update current_match %>
          </small>
          <%= link_to refresh_score_tournament_path(@tournament), remote: true, class: 'py-1 px-2 update-score-link' do %>
            <%= fa_icon "retweet" %>
          <% end %>
        </p>
      </li>
    <% end %>
    <% if next_match.present? %>
      <li class="list-group-item">
        <small>
          <%= t '.next' %><br>
          <%= court_label_for next_match %>
          <% unless next_match.not_before.blank? %>
            <br><%= t '.not_before' %> <%= next_match.not_before.strftime('%H:%M') %>
          <% end %>
        </small>
      </li>
    <% end %>
  </ul>
</p>

app/views/tournaments/_scripts_form.html.erb
<!-- Don't move this file to assets, scripts do not execute correctly on page load! -->

<script type='text/javascript'>
  // Functions

  // Draws X icon on .remove_fields elements
  function drawXIcons() {
    var removeLinks = $('.remove_fields');
    $(removeLinks).html('');
    $(removeLinks).append('<i class="fa fa-times"></i>');
  }


  // When document is ready...
  $(document).on('turbolinks:load', function() {
    drawXIcons();

    // Activate bootstrap tooltips
    $(function () {
      $('[data-toggle="tooltip"]').tooltip();
    });


    // Events

    // Suggest court label when new court-fields are being inserted
    $('#courts').on('cocoon:before-insert', function(e, insertedItem) {
      var calculatedCourtNr = $('#courts').find(".field").length + 1;
      $(insertedItem.find("input")[0]).val(calculatedCourtNr);
    });

    // Draw X icons after new court-field has been inserted
    $('#courts').on('cocoon:after-insert', function(e, insertedItem) {
      drawXIcons();
    });
  });
</script>

app/views/tournaments/_scripts_refresh_scores.html.erb
<script type="text/javascript">
  function refreshScores() {
    $.ajax({
      url: '<%= refresh_score_tournament_path @tournament %>'
    });
  }
</script>

app/views/tournaments/index.html.erb
<%= render 'shared/header' %>
<%= render 'shared/navbar' %>

app/views/tournaments/refresh_score.js.erb
$('#courts').html("<%= j render('courts') %>");
animateRefresh('span.score', 'rgba(224, 162, 123, 0.1)');

app/views/tournaments/show.html.erb
<%= render 'shared/header' %>
<%= render 'shared/navbar' %>
<% if @tournament.present? %>
  <div class="mb-2">
    <div class="row" id="courts">
      <%= render 'courts' %>
    </div>
  </div>
  <%= render 'shared/progress' %>
  <%= hidden_field_tag :court_public_keys %>

  <%= render 'scripts_refresh_scores' %>
  <%= render 'shared/scripts_idle_page_reload' %>
  <%= render 'shared/scripts_score_updated_page_reload' %>
<% else %>
  <p><%= t '.tournament_not_found' %></p>
<% end %>