config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|sk/ do
    root to: 'tournaments#index'
    get '/:locale' => 'tournaments#index'

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    get 'static_pages/about'

    resources :tournaments do
      resources :courts do
        post :reorder_matches, on: :member
        resources :matches, only: [:new] do
          post :reorder, on: :collection
        end
      end
      resources :matches do
        get :edit_score, on: :member
        post :update_score, on: :member
      end
      get :refresh_score, on: :member
    end
  end
end

app/views/shared/_footer.html.erb
<footer class="footer mt-2">
  <div class="row">
    <div class="col">
      <div class="background-clay-dark mt-1 py-4">
        <p class="text-center">
    			Tomáš Radič<br>
          <small>
            <%= link_to 'tomas.radic@gmail.com', 'mailto:tomas.radic@gmail.com' %><br>
            +421 905 289 248
          </small>
    		</p>
    		<p class="text-center">
          <small>
    				<%= link_to 'LinkedIn', 'https://www.linkedin.com/in/tomas-radic-a85161a7/', target: :_blank %>
    				●
    				<%= link_to 'Github', 'https://github.com/tomas-radic/scoreboard', target: :_blank %>
          </small>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="jumbotron my-0 pb-1 pt-4 background-clay-dark">
  <% if @tournament.present? %>
    <%= render 'shared/tournament_header' %>
  <% else %>
    <%= render 'shared/no_tournament_header' %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light mb-2 background-clay-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if @tournament.present? %>
        <li class="nav-item">
          <%= link_to t('.tournament'), tournament_path(@tournament), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('.matches'), tournament_matches_path(@tournament), class: 'nav-link' %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <% if controller_name == 'static_pages' && @tournament.blank? %>
          <li class="nav-item">
            <%= link_to t('.home'), root_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t('.sign_in'), new_user_session_path, class: 'nav-link'  %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to t('.about'), static_pages_about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= switch_locale_link request.url %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_no_tournament_header.html.erb
<h2><%= t('.tournament_not_found_caption') %></h2>
<% if user_signed_in? %>
  <% if current_user.tournament.present? %>
    <p><em><%= t '.goto_open_tournament_text' %></em></p>
    <p><%= link_to t('.goto_open_tournament'), tournament_path(current_user.tournament), class: 'btn btn-lg btn-success my-1' %></p>
  <% else %>
    <p><em><%= t '.open_tournament_text' %></em></p>
    <p><%= link_to t('.open_tournament'), new_tournament_path, class: 'btn btn-lg btn-success my-1' %></p>
  <% end %>
<% else %>
  <p><em><%= t '.keep_training_html' %></em></p>
<% end %>

app/views/shared/_progress.html.erb
<% unless @tournament_progress.blank? %>
  <div class="progress">
    <div class="progress-bar background-dust" role="progressbar" style="width: <%= @tournament_progress[:finished] %>%" aria-valuenow="<%= @tournament_progress[:finished] %>" aria-valuemin="0" aria-valuemax="100"></div>
    <div class="progress-bar background-highlight" role="progressbar" style="width: <%= @tournament_progress[:in_progress] %>%" aria-valuenow="<%= @tournament_progress[:in_progress] %>" aria-valuemin="0" aria-valuemax="100"></div>
    <div class="progress-bar background-clay-dark" role="progressbar" style="width: <%= @tournament_progress[:upcoming] %>%" aria-valuenow="<%= @tournament_progress[:upcoming] %>" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
<% end %>

app/views/shared/_scripts_idle_page_reload.html.erb
<!-- Don't move this file to assets, otherwise loaded on every page -->

<script type="text/javascript">
  var lastActivityTime = $.now();

  /*
  Hooks all possible user activity events and causes page to be reloaded if user
  becomes active after couple of minutes of inactivity
  */
  function hookIdleTracking() {
    var idleState = false;
    var idleTimer = null;

    $('*').bind('focus mousemove click mouseup mousedown keydown keypress keyup submit change mouseenter scroll resize dblclick', function () {
      var thisActivityTime = $.now();

      if ((thisActivityTime - lastActivityTime) > 240000) {
        refreshScores();  // this function to be defined on pages
      }

      lastActivityTime = thisActivityTime;
    });
  }

  $(document).on('turbolinks:load', function() {
    hookIdleTracking();
  });
</script>

app/views/shared/_scripts_refresh_scores.html.erb
<script type="text/javascript">
  function refreshScores() {
    location.reload();
  }
</script>

app/views/shared/_scripts_score_updated_page_reload.html.erb
<script type="text/javascript">
  $(document).on('turbolinks:load', function() {
    var courtPublicKeys = [];
    <% @court_public_keys.each do |key| %>
      courtPublicKeys.push('<%= key %>');
    <% end %>
    $('#court_public_keys').val(JSON.stringify(courtPublicKeys));
  });
</script>

app/views/shared/_tournament_header.html.erb
<h2><%= @tournament.label %></h2>
<% if policy(@tournament).manage? %>
  <p>
    <%= t '.close_tournament_text' %>
  </p>
  <p>
    <%= link_to t('.close_tournament'), tournament_path(@tournament), method: :delete, data: { confirm: t('.sure_destroy_tournament') }, class: 'btn btn-lg btn-danger my-1' %>
    <%= link_to t('.change'), edit_tournament_path(@tournament), class: 'btn btn-xs btn-link' %>
  </p>
<% else %>
  <p>
    <em><%= t '.welcome_html' %></em>
  </p>
<% end %>