config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|sk/ do
    root to: 'tournaments#index'
    get '/:locale' => 'tournaments#index'

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    get 'static_pages/about'

    resources :tournaments do
      resources :courts do
        post :reorder_matches, on: :member
        resources :matches, only: [:new] do
          post :reorder, on: :collection
        end
      end
      resources :matches do
        get :edit_score, on: :member
        post :update_score, on: :member
      end
      get :refresh_score, on: :member
    end
  end
end

app/models/court.rb
class Court < ApplicationRecord

  belongs_to :tournament
  has_many :matches, dependent: :destroy

  validates :label,
            :public_key, presence: true

  before_validation :set_defaults

  scope :sorted, -> { order(:label) }

  def current_match
    self.matches.where(finished_at: nil).where.not(started_at: nil).first
  end

  def next_match
    self.matches.where(finished_at: nil, started_at: nil).order(:position).first
  end

  private

  def set_defaults
    self.public_key ||= SecureRandom.hex
  end
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :load_records_or_redirect
  before_action :set_tournament_progress

  def show
    @court_occupations = {}
    court_matches_in_progress_count = @court.matches.in_progress.count
    @court_occupations[@court.id] = court_matches_in_progress_count if court_matches_in_progress_count > 0
    @court_public_keys = [@court.public_key]
    store_location
  end

  def reorder_matches
    # params[:matchPositionsOrder] comes like ['3', '1', '2', '4'] and we want to save
    # positions in this order

    @court.matches.sorted.each do |match|
      match.set_list_position(params[:matchPositionsOrder].index(match.position.to_s) + 1)
      match.save
    end

    respond_to do |format|
      format.js
    end
  end


  private

  def load_records_or_redirect
    @tournament = Tournament.find_by(id: params[:tournament_id])

    unless @tournament.present?
      redirect_to_root
      return
    end

    @court = @tournament.courts.find(params[:id])
    @matches_updatable = policy(@court.tournament).update_matches?
  end
end

app/helpers/courts_helper.rb
module CourtsHelper
  def courts_switch_link_class(page_court, court)
    result = 'nav-link btn btn-sm'
    result += ' active btn-outline-success' if page_court.id == court.id
    result
  end
end

app/views/courts/_courts_switch.html.erb
<ul class="nav nav-pills justify-content-center">
  <% @tournament.courts.sorted.each do |court| %>
    <li class="nav-item">
      <%=
        link_to court.label, tournament_court_path(@tournament, court),
            class: courts_switch_link_class(@court, court)
      %>
    </li>
  <% end %>
</ul>

app/views/courts/_matches_table.html.erb
<div class="table-responsive mb-1">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col"><%= t '.label' %></th>
        <th scope="col"><%= t '.score' %></th>
        <th scope="col"><%= t '.not_before' %></th>
      </tr>
    </thead>
    <tbody>
      <% @court.matches.sorted.each do |match| %>
        <%= content_tag :tr, class: decoration_class_for(match), data: { position: match.position } do %>
          <%=
            cells = handle_cell_for match, draggable: (@matches_updatable && !match.started?)
            cells += label_cell_for match, updatable: @matches_updatable
            cells += score_cell_for match, updatable: policy(match).update_score? && CourtDecorator.new(match.court).available_for?(match, @court_occupations)
            cells += content_tag :td do
              NotBeforeInfo.result_for match
            end

            cells
          %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/courts/_scripts_sort_matches.html.erb
<!-- Don't move this file to assets, accessing @tournament object -->

<script type="text/javascript">
  $(function(){
    // always pass csrf tokens on ajax calls
    $.ajaxSetup({
      headers: { 'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content') }
    });
  });

  function setMatchesTableSortable() {
    $('tbody').sortable({
      axis: 'y',
      update: function(event, ui) {
        var matchPositionsOrder = $('tr').map(function () {
          return $(this).data('position');
        }).get();

        $.ajax({
          data: {matchPositionsOrder:matchPositionsOrder},
          type: 'POST',
          url: '<%= reorder_matches_tournament_court_path @tournament, @court %>'
        });
      },
      handle: '.drag-handle'
    });
  }

  setMatchesTableSortable();
</script>

app/views/courts/reorder_matches.js.erb
$('#matches-table').html("<%= j render('matches_table') %>");
setMatchesTableSortable();

app/views/courts/show.html.erb
<%= render 'shared/header' %>
<%= render 'shared/navbar' %>
<%= render 'courts_switch' if @tournament.courts.count > 1 %>
<hr>
<p>
  <% if policy(@tournament).manage? %>
    <%= link_to t('.add_match'), new_tournament_court_match_path(@tournament, @court), class: 'btn btn-sm btn-success my-1' %>
  <% end %>
  <span class="float-right">
    <strong><%= t('.court_matches', label: @court.label) %></strong>
  </span>
</p>
<% if @court.matches.any? %>
  <div id="matches-table">
    <%= render 'matches_table' %>
  </div>
  <%= render 'shared/progress' %>
  <%= hidden_field_tag :court_public_keys %>
<% else %>
  <p><%= t '.no_matches' %></p>
<% end %>

<%= render 'shared/scripts_refresh_scores' %>
<%= render 'shared/scripts_idle_page_reload' %>
<%= render 'shared/scripts_score_updated_page_reload' %>

<% if @matches_updatable %>
  <%= javascript_include_tag 'touch_punch' %>
  <%= render 'scripts_sort_matches' %>
<% end %>