config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|sk/ do
    root to: 'tournaments#index'
    get '/:locale' => 'tournaments#index'

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    get 'static_pages/about'

    resources :tournaments do
      resources :courts do
        post :reorder_matches, on: :member
        resources :matches, only: [:new] do
          post :reorder, on: :collection
        end
      end
      resources :matches do
        get :edit_score, on: :member
        post :update_score, on: :member
      end
      get :refresh_score, on: :member
    end
  end
end

app/models/match.rb
class Match < ApplicationRecord

  belongs_to :court
  has_many :game_sets, dependent: :destroy
  delegate :tournament, to: :court

  MAX_PARTICIPANT_NAME_LENGTH = 30

  validates :participant1, :participant2, presence: true, length: { maximum: MAX_PARTICIPANT_NAME_LENGTH }
  validates :court, presence: true
  validate :court_occupied

  acts_as_list scope: :court

  scope :upcoming, -> { where(started_at: nil, finished_at: nil) }
  scope :in_progress, -> { where(finished_at: nil).where.not(started_at: nil) }
  scope :finished, -> { where.not(finished_at: nil) }
  scope :started, -> { where('started_at is not null or finished_at is not null') }
  scope :sorted, -> { includes(:court, :game_sets).order(:finished_at, :started_at, :position) }

  def label
    "#{participant1} vs #{participant2}"
  end

  def in_progress?
    self.finished_at.nil? && !self.started_at.nil?
  end

  def started?
    self.started_at.present? || self.finished_at.present?
  end

  def finished?
    self.finished_at.present?
  end


  private

  def court_occupied
    return unless self.in_progress?

    other_matches_on_court = self.court.matches.in_progress.where.not(id: self.id)

    if other_matches_on_court.any?
      errors.add :started_at, 'Court is occupied by other match'
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :edit_score, :update_score]
  before_action :load_tournament_or_redirect
  before_action :load_match, only: [:edit, :update, :edit_score, :update_score, :destroy]
  before_action :preprocess_params, only: [:create, :update]
  before_action :set_tournament_progress

  def index
    @matches = @tournament.matches.sorted
    @matches_updatable = policy(@tournament).update_matches?
    @court_occupations = court_occupations_of @tournament
    @court_public_keys = @tournament.courts.map(&:public_key)
    store_location
  end

  def new
    authorize @tournament, :manage?

    @match = Match.new(
      court_id: params[:court_id],
      game_sets: [
        GameSet.new,
        GameSet.new,
        GameSet.new
      ]
    )

    @back_path = stored_location(fallback: tournament_path(@tournament))
  end

  def create
    authorize @tournament, :manage?
    @match = CreateMatch.call(current_user.tournament, params).result

    if @match.errors.blank?
      redirect_to(stored_location(fallback: tournament_matches_path(@tournament))) and forget_location
    else
      @back_path = stored_location(fallback: tournament_path(@tournament))
      render :new
    end
  end

  def edit
    authorize @match
    @back_path = stored_location(fallback: tournament_path(@tournament))
  end

  def update
    authorize @match
    UpdateMatch.call(@match, params)

    if @match.errors.blank?
      redirect_to(stored_location(fallback: tournament_matches_path(@tournament))) and forget_location
    else
      @back_path = stored_location(fallback: tournament_path(@tournament))
      render :edit
    end
  end

  def destroy
    authorize @match

    @match.destroy
    redirect_to stored_location(fallback: tournament_path(@tournament))
  end

  def edit_score
    authorize @match

    redirect_to_court unless CourtDecorator.new(@match.court).available_for? @match, court_occupations_of(@tournament)
    @game_sets_count = @match.game_sets.count
  end

  def update_score
    begin
      back_to_edit_score = UpdateMatchState.call(
        @match,
        params[:score],
        params['finished'].present?
      ).result

      if back_to_edit_score
        redirect_to edit_score_tournament_match_path(@tournament, @match)
      else
        redirect_to tournament_matches_path @tournament
      end
    rescue ActiveRecord::RecordInvalid
      redirect_to tournament_court_path @tournament, @match.court
    end
  end


  private

  def load_tournament_or_redirect
    @tournament = Tournament.find_by(id: params[:tournament_id])

    unless @tournament.present?
      redirect_to tournament_path(id: params[:tournament_id]) and return
    end
  end

  def load_match
    @match = @tournament.matches.find(params[:id])
  end

  def preprocess_params
    if params[:match]['not_before(4i)'].blank?
        params[:match]['not_before(1i)'] = ""
        params[:match]['not_before(2i)'] = ""
        params[:match]['not_before(3i)'] = ""
        params[:match]['not_before(4i)'] = ""
        params[:match]['not_before(5i)'] = ""
    end
  end

  def redirect_to_court
    redirect_to tournament_court_path tournament_id: @match.tournament.id, id: @match.court_id
  end

  def court_occupations_of(tournament)
    tournament.courts.joins(:matches).merge(Match.in_progress).group('courts.id').count
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
  def handle_cell_for(match, draggable:)
    content_tag :td, class: draggable ? 'drag-handle' : '' do
      if draggable
        fa_icon 'bars'
      elsif match.finished?
        fa_icon 'check'
      end
    end
  end

  def label_cell_for(match, updatable:)
    content_tag :td do
      if updatable
        link_to match.label, edit_tournament_match_path(match.tournament, match)
      else
        match.label
      end
    end
  end

  def score_cell_for(match, updatable:)
    content_tag :td do
      if updatable
        link_to(Score.result_for(match), edit_score_tournament_match_path(match.tournament, match), class: 'btn btn-sm btn-success') + " <small><i>#{latest_score_update match, true}</i></small>".html_safe
      else
        "#{Score.result_for(match)} <small><i>#{latest_score_update match, true}</i></small>".html_safe
      end
    end
  end

  def decoration_class_for(match)
    if match.finished?
      'color-dust'
    elsif match.started?
      'background-highlight'
    else
      'background-clay-dark'
    end
  end

  def match_started_label(match)
    result = t '.match_started'
    result += " (#{match.started_at.in_time_zone.strftime('%H:%M')})" if match.started_at.present?
    result
  end

  def match_finished_label(match)
    result = t '.match_finished'
    result += " (#{match.finished_at.in_time_zone.strftime('%H:%M')})" if match.finished_at.present?
    result
  end

  def latest_score_update(match, bracket = false)
    latest_update_at = match.game_sets.map do |game_set|
      game_set.updated_at unless game_set.score.empty?
    end.compact.max

    return '' if latest_update_at.blank?

    minutes_ago = ((Time.zone.now - latest_update_at) / 60).ceil

    if minutes_ago >= 60
      bracket ? '(>60m)' : '>60m'
    elsif bracket
      t('latest_score_update_bracket_html', minutes: minutes_ago)
    else
      t('latest_score_update_html', minutes: minutes_ago)
    end
  end
end

app/views/matches/_form.html.erb
<hr>
<%= form_for [@tournament, @match] do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :participant1, t('.participant1') %>
        <%= f.text_field :participant1, class: add_error_class_to('form-control', @match, :participant1), maxlength: Match::MAX_PARTICIPANT_NAME_LENGTH %>
        <small class="float-right font-italic font-weight-light"><%= t('.max_length_notice', max_length: Match::MAX_PARTICIPANT_NAME_LENGTH) %></small>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :participant2, t('.participant2') %>
        <%= f.text_field :participant2, class: add_error_class_to('form-control', @match, :participant2), maxlength: Match::MAX_PARTICIPANT_NAME_LENGTH %>
        <small class="float-right font-italic font-weight-light"><%= t('.max_length_notice', max_length: Match::MAX_PARTICIPANT_NAME_LENGTH) %></small>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= f.label :court_id, t('.court') %>
        <%= f.select :court_id, @tournament.courts.sorted.map { |c| [c.label, c.id] }, {}, class: add_error_class_to('', @match, :court) %>
      </div>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= label_tag :max_sets_to_play, t('.max_sets_to_play') %>
        <span data-toggle="tooltip" data-placement="top", title="<%= t('.max_sets_to_play_info') %>">
          <%= fa_icon 'question-circle' %>
        </span>
        <%= number_field_tag :max_sets_to_play, @match.game_sets.size, min: 1, step: 2, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="form-group form-check">
        <%= check_box_tag :started, '1', @match.started_at.present?, class: add_error_class_to('form-check-input', @match, :started_at) %>
        <label class="form-check-label" for="started"><%= match_started_label @match %></label>
      </div>
    </div>
    <div class="col">
      <div class="form-group form-check">
        <%= check_box_tag :finished, '1', @match.finished_at.present?, class: 'form-check-input' %>
        <label class="form-check-label" for="finished"><%= match_finished_label @match %></label>
      </div>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= f.label :not_before, t('.not_before') %>
        <%= f.time_select :not_before, { minute_step: 15, include_blank: true } %>
      </div>
    </div>
  </div>

  <p class="text-right">
    <%= link_to t('.back'), @back_path, class: 'btn btn-lg btn-outline-success my-1' %>
    <%= f.submit t('.submit'), class: 'btn btn-lg btn-success my-1' %>
    <% if @match.persisted? %>
      <%= link_to t('.delete'), tournament_match_path(@tournament, @match), method: :delete, data: { confirm: t('.delete_confirmation') } %>
    <% end %>
  </p>
<% end %>

<%= render 'scripts_form' %>

app/views/matches/_scripts.html.erb
<script type="text/javascript">
  $('.increment').click(function() {
    var textField = $(this).parent().prev();
    var currentValue = parseInt(textField.val());
    var newValue = 1;

    if (!isNaN(currentValue)) {
      newValue = currentValue + 1;
    }

    textField.val(newValue);
  });
</script>

app/views/matches/_scripts_edit_score.html.erb
<script type="text/javascript">
  $('.increment').click(function() {
    var textField = $(this).parent().prev();
    var currentValue = parseInt(textField.val());
    var newValue = 1;

    if (!isNaN(currentValue)) {
      newValue = currentValue + 1;
    }

    textField.val(newValue);
  });
</script>

app/views/matches/_scripts_form.html.erb
<script type="text/javascript">
  $(document).on('turbolinks:load', function() {

    // Activate bootstrap tooltips
    $(function () {
      $('[data-toggle="tooltip"]').tooltip();
    });
  });
</script>

app/views/matches/edit.html.erb
<h2><strong><%= t '.edit_match' %></strong></h2>
<%= render 'form' %>

app/views/matches/edit_score.html.erb
<h1><%= @match.label %></h1>
<%= form_tag update_score_tournament_match_path(@tournament, @match) do %>
  <% @match.game_sets.each_with_index do |game_set, i| %>
    <hr/>
    <h3><%= "Set #{game_set.position}" %></h3>
    <div class="row">
      <div class="col-6">
        <div class="form-group">
          <div class="input-group">
            <%= number_field_tag :score, game_set.score.first, min: 0, step: 1,
                name: "score[#{game_set.position-1}][]", class: 'form-control float-right text-right replace-input-field' %>
            <div class="input-group-append">
              <button class="btn btn-success increment" type="button">+</button>
            </div>
          </div>
          <p class="text-right"><small><%= @match.participant1 %></small></p>
        </div>
      </div>
      <div class="col-6">
        <div class="form-group">
          <div class="input-group">
            <%= number_field_tag :score, (game_set.score.last), min: 0, step: 1,
                name: "score[#{game_set.position-1}][]", class: 'form-control float-left text-left replace-input-field' %>
            <div class="input-group-append">
              <button class="btn btn-success increment" type="button">+</button>
            </div>
          </div>
          <p><small><%= @match.participant2 %></small></p>
        </div>
      </div>
    </div>
    <% if i < (@game_sets_count - 1) %>
      <div class="row">
        <div class="col">
          <p class="content-center">
            <%= submit_tag t('.submit'), class: 'btn btn-block btn-sm btn-success d-sm-none d-block' %>
            <%= submit_tag t('.submit'), class: 'btn btn-sm btn-success d-none d-sm-block' %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>
  <hr/>

  <div class="row my-2">
    <div class="col">
      <div class="form-check">
        <%= check_box_tag :finished, '1', @match.finished_at.present?, class: 'form-check-input' %>
        <label class="form-check-label" for="finished"><%= match_finished_label @match %></label>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <p class="content-center">
        <%= submit_tag t('.submit'), class: 'btn btn-block btn-lg btn-success d-sm-none d-block' %>
        <%= submit_tag t('.submit'), class: 'btn btn-lg btn-success d-none d-sm-block' %>
      </p>
      <p class="content-center">
        <%= link_to t('.quit'), tournament_court_path(@tournament, @match.court) %>
      </p>
    </div>
  </div>
<% end %>

<%= render 'scripts_edit_score' %>

app/views/matches/index.html.erb
<%= render 'shared/header' %>
<%= render 'shared/navbar' %>
<p>
  <% if policy(@tournament).manage? %>
    <%= link_to t('.add_match'), new_tournament_match_path(@tournament), class: 'btn btn-sm btn-success my-1' %>
  <% end %>
  <span class="float-right"><strong><%= t '.all_planned_matches' %></strong></span>
</p>
<% if @matches.any? %>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col"><%= t '.label' %></th>
          <th scope="col"><%= t '.court' %></th>
          <th scope="col"><%= t '.score' %></th>
          <th scope="col"><%= t '.not_before' %></th>
        </tr>
      </thead>
      <tbody>
        <% @matches.each do |match| %>
          <%= content_tag :tr, class: decoration_class_for(match) do %>
            <%=
              cells = content_tag :td do
                fa_icon 'check' if match.finished?
              end

              cells += label_cell_for match, updatable: @matches_updatable
              cells += content_tag :td do
                link_to match.court.label, tournament_court_path(match.tournament, match.court), class: 'btn btn-sm btn-success'
              end
              cells += score_cell_for match, updatable: policy(match).update_score? && CourtDecorator.new(match.court).available_for?(match, @court_occupations)
              cells += content_tag :td do
                NotBeforeInfo.result_for match
              end

              cells
            %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= render 'shared/progress' %>
  <%= hidden_field_tag :court_public_keys %>
<% else %>
  <p><%= t '.no_matches' %></p>
<% end %>

<%= render 'shared/scripts_refresh_scores' %>
<%= render 'shared/scripts_idle_page_reload' %>
<%= render 'shared/scripts_score_updated_page_reload' %>

app/views/matches/new.html.erb
<h2><strong><%= t '.new_match' %></strong></h2>
<%= render 'form' %>